version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./bastiodon:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - bastiodon_network
    command: python manage.py runserver 0.0.0.0:8000

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - bastiodon_network
    ports:
      - "6379:6379"

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - bastiodon_network

networks:
  bastiodon_network:
    driver: bridge

volumes:
  redis_data: